import {
  ArrowUp,
  BadgeCheck,
  Clipboard,
  Download,
  ExternalLink,
  Folder,
  Heart,
  Paintbrush,
  Plus,
  Puzzle,
  RefreshCw,
  Video,
  X,
} from "lucide-react";

export const Icons = {
  Folder,
  Heart,
  PaintBrush: Paintbrush,
  ArrowUp,
  Plus,
  XMark: X,
  ArrowPath: RefreshCw,
  ClipboardDocument: Clipboard,
  Download,
  ArrowTopRight: ExternalLink,
  CheckBadge: BadgeCheck,
  PuzzlePiece: Puzzle,
  VideoCamera: Video,
};
